= Testing Solace broker with Apache Camel

https://camel.apache.org/[Apache Camel] is well-known an open-source, Java-based framework for building messaging and integration solutions. 

*Camel Solace PubSub Test* is a simple application that can be used to test the Event Broker. It's based on https://docs.redhat.com/en/documentation/red_hat_fuse/[Red Hat Fuse 7] which is the enterprise ready version of Camel on Spring Boot runtime.

* GitHub: https://github.com/bszeti/camel-solace-pubsub-test
* Quay: ??

The app is useful to test different messaging use cases and reproduce issues experienced in more complex architectures or production environment. Using Camel's event driven nature - and Spring Boot's convention over configuration policy - makes it simple to extend or modify the routes to specific scenarios.

=== Core features:

* *Send messages*
** Set message body and headers
** Generated large body and headers
** Send by multiple threads
** Given count and pace
** Retries
** Transacted send
* *Receive message*
** Multiple consumers
** Consumer cashing
** Transacted consumers
** Receive and forward (in transaction)
* *Connection pooling*
** Spring CachingConnectionFactory
** MessagingHub PooledJMS

=== Protocols:

[cols="1,3"]
|===
| *connection.type*
| *TLS URL*
| SOLACE 
| `tcps://smf-pubsubplus-helm.apps.your_cluster_domain.com:443`
| SOLACE (over websocket)
| `wss://smfweb-pubsubplus-helm.apps.your_cluster_domain.com:443`
| AMQP
| `amqps://amqp-pubsubplus-helm.apps.your_cluster_domain.com:443`
| MQTT
| `ssl://mqtt-pubsubplus-helm.apps.your_cluster_domain.com:443`
| MQTT (over websocket)
| `wss://mqttweb-pubsubplus-helm.apps.your_cluster_domain.com:443`
|===

=== Example

See all the parameters in https://github.com/bszeti/camel-solace-pubsub-test/blob/main/src/main/resources/application.properties[application.properties]

Example config to send a message:
[source,properties]
----
connection.type=SOLACE
connection.remoteUrl=tcps://smf-pubsubplus.apps.your_cluster_domain:443
connection.username=test
connection.password=secret
connection.useCachingConnectionFactory=true
connection.sessionCacheSize=10
connection.clientId=sender

send.count=1
send.enabled=true
send.queue=q1
send.message.length=100
send.headers.count=2
send.headers.length=20
----